name: Build Dev Images

on:
  pull_request:
    branches:
      - dev

env:
  PRODUCT_VERSION: "latest"
  AMI_IMAGE_ID: ""
  AMI_PREFIX: "rhel-9-cis"
  AWS_REGION: "us-east-2"
  AWS_ROLE_NAME: "AWSPackerSSMRole"
  AWS_SG_ID: ${{ secrets.AWS_SG_ID }}
  AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
  AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}
  OS_VERSION: "Red Hat Enterprise Linux 9"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build RHEL9 AMI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packer dependencies
        run: |
          pip install -r requirements.txt
          curl -k https://releases.hashicorp.com/packer/1.9.1/packer_1.9.1_linux_amd64.zip --output packer.zip
          unzip packer.zip && mv -f packer /usr/local/bin

      - name: Install ansible roles
        run: |
          ansible-galaxy install RedHatOfficial.rhel9_cis
          sed -i '/socket_file_exists.stdout_lines/d' /home/runner/.ansible/roles/RedHatOfficial.rhel9_cis/tasks/main.yml
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Run `packer init`
        id: init
        run: packer init ./rhel9_aws_cis.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: packer validate ./rhel9_aws_cis.pkr.hcl

      - name: Build Artifact
        run: packer build -on-error=abort -var "ami_image_id=${{ env.ami_image_id }}" -var "ami_prefix=${{ env.AMI_PREFIX }}" -var "aws_region=${{ env.AWS_REGION }}" -var "aws_role_name=${{ env.AWS_ROLE_NAME }}" -var "aws_subnet_id=${{ env.AWS_SUBNET_ID }}" -var "aws_vpc_id=${{ env.AWS_VPC_ID }}" ./rhel9_aws_cis.pkr.hcl